### ISSUE TITLE
aiohttp_session error

### ISSUE THREAD

**Issue by sefsh** [Lykos153/maubot-spotify#30]
Can't load the plugin. I'm on Docker maubot:latest.

```
[11:45:46](file:////opt/maubot/maubot/loader/zip.py:203)ERRORmaubot.loader.zipFailed to load org.booq.spotifybot v0.1.0
[11:45:46](file:////opt/maubot/maubot/loader/zip.py:203)ERRORmaubot.loader.zipTraceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 216, in _load
    importer.load_module(module)
  File "/opt/maubot/maubot/lib/zipimport.py", line 280, in load_module
    exec(code, mod.__dict__)
  File "/data/plugins/org.booq.spotifybot-v0.1.0.mbp/spotifybot/__init__.py", line 1, in <module>
    from .bot import SpotifyBot
  File "<frozen zipimport>", line 259, in load_module
  File "/data/plugins/org.booq.spotifybot-v0.1.0.mbp/spotifybot/bot.py", line 8, in <module>
    from aiohttp_session import (
ModuleNotFoundError: No module named 'aiohttp_session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 201, in load
    return self._load(reset_cache)
  File "/opt/maubot/maubot/loader/zip.py", line 220, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module spotifybot
[11:45:46](file:////opt/maubot/maubot/management/api/middleware.py:68)ERRORmaubot.serverError in handler
[11:45:46](file:////opt/maubot/maubot/management/api/middleware.py:68)ERRORmaubot.serverTraceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 216, in _load
    importer.load_module(module)
  File "/opt/maubot/maubot/lib/zipimport.py", line 280, in load_module
    exec(code, mod.__dict__)
  File "/data/plugins/org.booq.spotifybot-v0.1.0.mbp/spotifybot/__init__.py", line 1, in <module>
    from .bot import SpotifyBot
  File "<frozen zipimport>", line 259, in load_module
  File "/data/plugins/org.booq.spotifybot-v0.1.0.mbp/spotifybot/bot.py", line 8, in <module>
    from aiohttp_session import (
ModuleNotFoundError: No module named 'aiohttp_session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/maubot/management/api/middleware.py", line 49, in error
    return await handler(request)
  File "/opt/maubot/maubot/management/api/instance.py", line 83, in update_instance
    return await _create_instance(instance_id, data)
  File "/opt/maubot/maubot/management/api/instance.py", line 59, in _create_instance
    await instance.start()
  File "/opt/maubot/maubot/instance.py", line 361, in start
    cls = await self.loader.load()
  File "/opt/maubot/maubot/loader/zip.py", line 201, in load
    return self._load(reset_cache)
  File "/opt/maubot/maubot/loader/zip.py", line 220, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module spotifybot

**Comment by sefsh** [comment]
I solved this by manually installing `aiohttp_session` and `spotipy2` manually with `pip install aiohttp_session spotipy2` after first entering the running container with `docker exec -it matrix_maubot /bin/sh`
